server:
  port: ${APP_SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable specific-language documentations
      - swaggerEN
  zipkin:
    enabled: false
  sleuth:
    baggage:
      remote-fields: X-Client-Ip
      correlation-fields: X-Client-Ip

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"


logging:
  level:
    it.pagopa.selfcare: ${APP_LOG_LEVEL:DEBUG}
  pattern:
    additional-info: ",%X{X-Client-Ip:-}]"
