server:
  port: ${APP_SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      # TO enable specific-language documentations
      - swaggerEN
      - AzureStorage
  data:
    web:
      pageable:
        max-page-size: ${MAX_PAGE_SIZE:2000}
  zipkin:
    enabled: false
  sleuth:
    baggage:
      remote-fields: X-Client-Ip
      correlation-fields: X-Client-Ip

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"


logging:
  level:
    it:
      pagopa:
        selfcare: ${APP_LOG_LEVEL:DEBUG}
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
  pattern:
    additional-info: ",%X{X-Client-Ip:-}]"

core:
  user-event-service:
    type: ${CORE_USER_EVENT_SERVICE_TYPE:ignore}
  contract-event-service:
    type: ${CORE_CONTRACT_EVENT_SERVICE_TYPE:ignore}
