server:
  port: ${APP_SERVER_PORT:8080}
  shutdown: graceful

spring:
  application:
    name: "selc-ms-core"
    version: "1.0-SNAPSHOT"
  profiles:
    include:
      # TO enable specific-language documentations
      - swaggerEN
  zipkin:
    enabled: false
  sleuth:
    baggage:
      remote-fields: X-Client-Ip
      correlation-fields: X-Client-Ip

info:
  build:
    artifact: "selc-ms-core"
    name: "selc-ms-core"
    description: "Microservice to manage Self Care NAME"
    version: "1.0-SNAPSHOT"


logging:
  level:
    it.pagopa.selfcare: ${APP_LOG_LEVEL:DEBUG}
  pattern:
    additional-info: ",%X{X-Client-Ip:-}]"
