image:
  repository: selcdacr.azurecr.io/selfcaremscore

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - selc.internal.dev.selfcare.pagopa.it
      secretName: selc-internal-dev-selfcare-pagopa-it
  hosts:
    - host: "selc.internal.dev.selfcare.pagopa.it"
      paths:
        - path: /ms-core/v1/(.*)
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 500m
    memory: 600M
  limits:
    cpu: 2000m
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  EXTERNAL_API_LOG_LEVEL: "DEBUG"
  CORE_USER_EVENT_SERVICE_TYPE: "send"
