image:
  repository: selcpacr.azurecr.io/selfcaremscore
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 1.0-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it,https://api.platform.pagopa.it"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

pdb:
  enabled: true
  minAvailable: 2

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  EXTERNAL_API_LOG_LEVEL: "INFO"
