image:
  repository: selcuacr.azurecr.io/selfcaremscore
  tag: 1.0-SNAPSHOT

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://uat.selfcare.pagopa.it,http://localhost:3000"
  tls:
    - hosts:
        - selc.internal.uat.selfcare.pagopa.it
      secretName: selc-internal-uat-selfcare-pagopa-it
  hosts:
    - host: "selc.internal.uat.selfcare.pagopa.it"
      paths:
        - path: /ms-core/v1/(.*)
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 500m
    memory: 700M
  limits:
    cpu: 1600m
    memory: 900M

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_TOOL_OPTIONS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  EXTERNAL_API_LOG_LEVEL: "DEBUG"
  CORE_USER_EVENT_SERVICE_TYPE: "send"
  CORE_CONTRACT_EVENT_SERVICE_TYPE: "send"
