on:
  workflow_call:
    inputs:
      pr_number:
        type: string
        required: true
      module:
        type: string
        required: true
      source_branch:
        type: string
        required: true
      target_branch:
        type: string
        required: true
      sonar_key:
        type: string
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  code_review:
    name: 'Build & Analysis'
    runs-on: ubuntu-20.04
    permissions:
      packages: read

    steps:

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@fa2c7e4517ed008b1f73e7e0195a9eecf5582cd4
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: 'temurin'
          maven-version: '3.9.5'
          cache-enabled: true

      - name: Build
        run: |
          mvn -f ./pom.xml \
          -B \
          clean org.jacoco:jacoco-maven-plugin:prepare-agent \
          verify org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:report-aggregate

      - name: Analyze
        run: |
          xmlReportPaths=$(find "$(pwd)" -path '*jacoco.xml' | sed 's/.*/&/' | tr '\n' ',');

          mvn -f pom.xml -B \
            -Dsonar.coverage.jacoco.xmlReportPaths=$xmlReportPaths \
            -Dsonar.organization=pagopa \
            -Dsonar.projectKey=${{ inputs.sonar_key }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.pullrequest.key=${{ inputs.pr_number }} \
            -Dsonar.pullrequest.branch=${{ inputs.source_branch }} \
            -Dsonar.pullrequest.base=refs/remotes/origin/${{ inputs.target_branch }} \
            -Dsonar.exclusions='**/enums/**, **/model/**, **/constant/**, **/*Constant*, **/*Config.java, **/*Scheduler.java, **/*Application.java, **/src/test/**, **/Dummy*.java'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # - name: Build and Analyze
      #   shell: bash
      #   run: |
      #     mvn --projects :test-coverage --also-make verify -P${{ inputs.module }},report,coverage \
      #       -Dsonar.organization=pagopa \
      #       -Dsonar.projectKey=${{ inputs.sonar_key }} \
      #       -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
      #       -Dsonar.pullrequest.key=${{ inputs.pr_number }} \
      #       -Dsonar.pullrequest.branch=${{ inputs.source_branch }} \
      #       -Dsonar.pullrequest.base=refs/remotes/origin/${{ inputs.target_branch }} \
      #       -Dsonar.exclusions='**/enums/**, **/model/**, **/constant/**, **/*Constant*, **/*Config.java, **/*Scheduler.java, **/*Application.java, **/src/test/**, **/Dummy*.java'
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
