name: Code Review ms-core

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main
      - releases/**
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - '.github/workflows/pr_ms.yml'
      - '.github/workflows/release_ms.yml'
      - '.github/workflows/release_ms_pnpg.yml'
      - '!.devops/**'
      - '!.identity/**'
      - '!helm/**'
      - '!**.md'
      - '!**ignore'
      - '!infra/**'
      - '!.terraform-version'
      - '!CODEOWNERS'

jobs:

  code_review:
    uses: pagopa/selfcare-commons/.github/workflows/call_code_review_spring.yml@main
    name: 'Code Review'
    secrets: inherit
    if: github.base_ref == 'main' && github.event_name == 'pull_request'
    with:
      pr_number: ${{ github.event.pull_request.number }}
      source_branch: ${{ github.head_ref }}
      target_branch: ${{ github.base_ref }}
      sonar_key: 'pagopa_selfcare-ms-core'

  docker_build:
    uses: pagopa/selfcare-commons/.github/workflows/call_code_review_docker.yml@main
    name: 'Docker'
