name: Release - ms-core

on:
  push:
    branches:
      - main
      - releases/**
    paths:
      - '!.devops/**'
      - '!.github/**'
      - '!.identity/**'
      - '!helm/**'
      - '!**.md'
      - '!.**ignore'
      - '!infra/**'
      - '!.terraform-version'
      - '!CODEOWNERS'

  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        options: 
        - dev
        - uat
        - prod

jobs:

  release_dev:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[Dev] Core ms Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') != true && inputs.env == null) || inputs.env == 'dev' }}
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev
      dir: 'infra/container_apps'

  release_uat:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[UAT] Core ms Release'
    if: ${{ (startsWith(github.ref_name, 'releases/') == true && inputs.env == null) || inputs.env == 'uat' }}
    secrets: inherit
    with:
      environment: uat
      tf_environment: uat
      dir: 'infra/container_apps'

  release_prod:
    uses: pagopa/selfcare-commons/.github/workflows/call_release_docker.yml@main
    name: '[Prod] Core ms Release'
    if: ${{ inputs.env == 'prod' }}
    secrets: inherit
    with:
      environment: prod
      tf_environment: prod
      dir: 'infra/container_apps'