name: Deploy Container Apps infra

on:
  push:
    branches:
      - main
      - releases/**
    paths:
      - './infra/container_apps/ms-core/env/dev-pnpg'
      - './infra/container_apps/ms-core/env/uat-pnpg'
      - './infra/container_apps/ms-core/env/prod-pnpg'
      - '!./infra/container_apps/ms-core/env/**'
      - './infra/container_apps/ms-core/**'

  workflow_dispatch:

jobs:

  release_dev:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[Dev] Container Apps Infra Release'
    if: github.ref_name == 'main'
    secrets: inherit
    with:
      environment: dev
      tf_environment: dev-pnpg
      dir: ./infra/container_apps/ms-core
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})

  release_uat:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[UAT] Container Apps Infra Release'
    if: startsWith(github.ref_name, 'releases/')
    secrets: inherit
    with:
      environment: uat
      tf_environment: dev-pnpg
      dir: ./infra/container_apps/ms-core
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})

  release_prod:
    uses: ./.github/workflows/call_release_infra.yml
    name: '[Prod] Container Apps Infra Release'
    if: startsWith(github.ref_name, 'releases/')
    secrets: inherit
    with:
      environment: prod
      tf_environment: dev-pnpg
      dir: ./infra/container_apps/ms-core
      env_vars: |
        TF_VAR_image_tag=sha-$(git rev-parse --short ${{ github.sha }})
