name: Swagger Detect Conflict and Update
on:
  pull_request:
    branches:
      - release-dev
    types: [ opened, synchronize, reopened ]
    
permissions:
  contents: write

jobs:
  swagger_conflict_update:  
    runs-on: ubuntu-20.04
    permissions: write-all
    name: Swagger Detect Conflict and Update
    steps:
      - id: swagger-conflict-update
        uses: pagopa/selfcare-commons/github-actions-template/swagger-detect-conflict-spring@main
        with:
          path_openapi_docs: app/src/main/resources/swagger/api-docs.json
          branch_ref: release-dev